name: todo
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1
  provider: ^5.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  intl: ^0.18.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
flutter:
  uses-material-design: true
